import { ToolDefinition, ToolHandler, ToolResult } from './types';
import { nbaQueryHandler } from './nba';
import { createDirectoryHandler, writeFileHandler } from './filesystem';
import { assertPermission } from '../config-manager';

export const sportsReportDef: ToolDefinition = {
  name: 'generate_sports_report',
  description: 'Generate a sports results report (NBA) and save it to the specified directory on the desktop',
  category: 'utility',
  // This tool creates files on disk, so it requires `write_file` permission
  requiredPermissions: ['write_file'],
  parameters: {
    type: 'object',
    properties: {
      league: { type: 'string', description: 'League to report on', default: 'nba' },
      date: { type: 'string', description: 'Date for games (YYYY-MM-DD). Defaults to today.', default: '' },
      directory: { type: 'string', description: 'Directory to create (e.g. "Desktop/NBA Results")', default: 'Desktop/NBA Results' },
      format: { type: 'string', description: 'Report format: html or txt', enum: ['html', 'txt'], default: 'html' },
      includeSummary: { type: 'boolean', description: 'Include summary paragraph', default: true }
    },
    required: ['league']
  }
};

function formatDate(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

export const sportsReportHandler: ToolHandler = async (args, context): Promise<ToolResult> => {
  try {
    const league = (args.league || 'nba').toLowerCase();
    if (league !== 'nba') return { success: false, error: `Unsupported league: ${league}` };

    // Require explicit write permission to create files
    // Check transient override (allow once) before asserting global permission
    if (!((context as any)?.overrideAllowed?.includes('write_file') || assertPermission('write_file'))) {
      return { success: false, error: 'Permission denied: write_file is disabled. Enable the Write File permission in Settings to allow report generation.' };
    }

    const date = args.date || formatDate(new Date());

    // Query games for the date
    const nbaResp = await nbaQueryHandler({ type: 'games', date, perPage: 50 }, {} as any);
    if (!nbaResp.success) return { success: false, error: `Failed to fetch NBA data: ${nbaResp.error}` };

    const events = (nbaResp.result && nbaResp.result.events) || [];

    // Create directory
    const createResp = await createDirectoryHandler({ path: args.directory || 'Desktop/NBA Results' }, {} as any);
    if (!createResp.success) return { success: false, error: `Failed to create directory: ${createResp.error}` };

    // Build report
    const title = `This Week's NBA Results - ${date}`;

    if ((args.format || 'html') === 'txt') {
      let txt = `${title}\nDate: ${date}\n\nGames:\n`;
      for (const e of events) {
        const name = e.name || e.shortName || (e.competitions && e.competitions[0] && e.competitions[0].competitors && e.competitions[0].competitors.map((c: any) => c.team?.displayName).join(' vs ')) || 'Game';
        const score = (e.competitions && e.competitions[0] && e.competitions[0].competitors) ? e.competitions[0].competitors.map((c: any) => `${c.team?.abbreviation || c.team?.displayName || ''} ${c.score || ''}`).join(' — ') : '';
        txt += `- ${name} ${score}\n`;
      }

      if (args.includeSummary) txt += `\nSummary:\nGenerated by SADIE (demo).`;

      const writeResp = await writeFileHandler({ path: `${createResp.result.path}/report.txt`, content: txt, append: false }, {} as any);
      if (!writeResp.success) return { success: false, error: `Failed to write report: ${writeResp.error}` };

      return { success: true, result: { path: createResp.result.path, files: [writeResp.result.path || `${createResp.result.path}/report.txt`] } } as any;
    }

    // HTML format
    let html = `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title></head><body><h1>${title}</h1><p><strong>Date:</strong> ${date}</p><table border="1" cellpadding="8" cellspacing="0"><thead><tr><th>Game</th><th>Score</th></tr></thead><tbody>`;
    for (const e of events) {
      const name = e.name || e.shortName || (e.competitions && e.competitions[0] && e.competitions[0].competitors && e.competitions[0].competitors.map((c: any) => c.team?.displayName).join(' vs ')) || 'Game';
      const score = (e.competitions && e.competitions[0] && e.competitions[0].competitors) ? e.competitions[0].competitors.map((c: any) => `${c.team?.abbreviation || c.team?.displayName || ''} ${c.score || ''}`).join(' — ') : '';
      html += `<tr><td>${name}</td><td>${score}</td></tr>`;
    }
    html += `</tbody></table>`;
    if (args.includeSummary) html += `<h2>Summary</h2><p>Generated by SADIE.</p>`;
    html += `</body></html>`;

    const writeResp = await writeFileHandler({ path: `${createResp.result.path}/report.html`, content: html, append: false }, {} as any);
    if (!writeResp.success) return { success: false, error: `Failed to write HTML report: ${writeResp.error}` };

    return { success: true, result: { path: createResp.result.path, files: [writeResp.result.path || `${createResp.result.path}/report.html`] } } as any;
  } catch (err: any) {
    return { success: false, error: `Sports report generation failed: ${err.message}` };
  }
};

export default {
  definition: sportsReportDef,
  handler: sportsReportHandler
};